/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import converted.avro.User;
import org.apache.avro.Schema;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.specific.SpecificDatumWriter;

import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        app.init();
    }

    public void init(){
        User user = new User();
        user.setName("Bob");
        user.setFavoriteNumber(555);
        user.setFavoriteColor("Red");

        System.out.println(user.getName());
        System.out.println(user.getFavoriteNumber());
        System.out.println(user.getFavoriteColor());

        Schema schema = user.getSchema();
        schema.addAlias("someNewAlias1");
//        Set<String> aliases = schema.getAliases();
//        schema.addAlias("someNewAlias2");
//        schema.addAlias("someNewAlias3");
        writeToFile(user);
    }

    //  writes specified user data to a hardcoded file.
    public void writeToFile(User user){
        DatumWriter<User> userDatumWriter = new SpecificDatumWriter<User>(User.class);
        DataFileWriter<User> dataFileWriter = new DataFileWriter<User>(userDatumWriter);
        try{
            dataFileWriter.create(user.getSchema(), new File("users.avro"));
            dataFileWriter.append(user);
            dataFileWriter.close();
        }   catch(IOException e){
            e.printStackTrace();
        }
    }
}
